# Generated by Django 4.1.3 on 2022-11-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="bio",),
        migrations.RemoveField(model_name="profile", name="birth_date",),
        migrations.RemoveField(model_name="profile", name="hobby",),
        migrations.AddField(
            model_name="profile", name="refdate", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="profile", name="referent", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="reflink",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="refnumber",
            field=models.IntegerField(default=0),
        ),
    ]
