# Generated by Django 4.1.3 on 2022-12-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_order"),
    ]

    operations = [
        migrations.DeleteModel(name="Order",),
    ]
