# Generated by Django 4.1.3 on 2022-12-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile", name="paid", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="profile", name="paiddate", field=models.DateField(null=True),
        ),
    ]
